""""sync_user_settings_and_cleanup"

Revision ID: 0ae5df15b305
Revises: c6b4627fe974
Create Date: 2026-04-06 19:32:40.650876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ae5df15b305'
down_revision: Union[str, Sequence[str], None] = 'c6b4627fe974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS "Post" CASCADE')
    op.execute('DROP TABLE IF EXISTS "View" CASCADE')
    op.execute('DROP TABLE IF EXISTS "Comment" CASCADE')
    op.execute('DROP TABLE IF EXISTS "Repost" CASCADE')
    op.execute('DROP TABLE IF EXISTS "Video" CASCADE')
    op.execute('DROP TABLE IF EXISTS "VerificationCode" CASCADE')
    op.execute('DROP TABLE IF EXISTS "User" CASCADE')
    op.execute('DROP TABLE IF EXISTS "Like" CASCADE')
    op.execute('DROP TABLE IF EXISTS "Follow" CASCADE')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_wins', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_trophies', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notif_new_follower', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notif_challenge_win', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notif_comments', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notif_likes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_weekly', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_challenges', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_payouts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_marketing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payout_method', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('payout_method')
        batch_op.drop_column('email_marketing')
        batch_op.drop_column('email_payouts')
        batch_op.drop_column('email_challenges')
        batch_op.drop_column('email_weekly')
        batch_op.drop_column('notif_likes')
        batch_op.drop_column('notif_comments')
        batch_op.drop_column('notif_challenge_win')
        batch_op.drop_column('notif_new_follower')
        batch_op.drop_column('show_trophies')
        batch_op.drop_column('show_wins')

    op.create_table('Follow',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('follower_id <> followed_id', name=op.f('Follow_check')),
    sa.ForeignKeyConstraint(['followed_id'], ['User.id'], name=op.f('Follow_followed_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['User.id'], name=op.f('Follow_follower_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id', name=op.f('Follow_pkey'))
    )
    with op.batch_alter_table('Follow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_follow_follower'), ['follower_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_follow_followed'), ['followed_id'], unique=False)

    op.create_table('Like',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('Like_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['Video.id'], name=op.f('Like_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'video_id', name=op.f('Like_pkey'))
    )
    with op.batch_alter_table('Like', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_like_video'), ['video_id'], unique=False)

    op.create_table('User',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_premium', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_onboarded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('profile_pic', sa.VARCHAR(), server_default=sa.text("'http://localhost:8000/static/defaults/default_avatar.png'::character varying"), autoincrement=False, nullable=True),
    sa.Column('flash_uploads', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('home_uploads', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('User_pkey')),
    sa.UniqueConstraint('email', name=op.f('User_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('google_id', name=op.f('User_google_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('User_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_google_id'), ['google_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_email'), ['email'], unique=False)

    op.create_table('VerificationCode',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('VerificationCode_pkey'))
    )
    with op.batch_alter_table('VerificationCode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_verification_email'), ['email'], unique=False)

    op.create_table('Video',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url_480p', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url_720p', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url_1080p', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url_2k', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url_4k', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('video_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('views', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('earnings', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('shares', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('processing_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['User.id'], name=op.f('Video_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Video_pkey'))
    )
    with op.batch_alter_table('Video', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_video_type'), ['video_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_video_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_video_owner'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_video_created'), [sa.literal_column('created_at DESC')], unique=False)

    op.create_table('Repost',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('Repost_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['Video.id'], name=op.f('Repost_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Repost_pkey'))
    )
    with op.batch_alter_table('Repost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_repost_video'), ['video_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_repost_user'), ['user_id'], unique=False)

    op.create_table('Comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['User.id'], name=op.f('Comment_owner_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['Video.id'], name=op.f('Comment_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Comment_pkey'))
    )
    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_comment_video'), ['video_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_comment_owner'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_comment_created'), [sa.literal_column('created_at DESC')], unique=False)

    op.create_table('View',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('View_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['Video.id'], name=op.f('View_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('View_pkey'))
    )
    with op.batch_alter_table('View', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_view_video'), ['video_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_view_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_view_created'), ['created_at'], unique=False)

    op.create_table('Post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['User.id'], name=op.f('Post_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Post_pkey'))
    )
    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_post_owner'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_post_created'), [sa.literal_column('created_at DESC')], unique=False)

    # ### end Alembic commands ###
