"""add watch_history column to user_recommendation_profiles

Revision ID: 219cc7d232b2
Revises: b1506accc1d5
Create Date: 2026-04-16 03:04:22.759263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219cc7d232b2'
down_revision: Union[str, Sequence[str], None] = 'b1506accc1d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_recommendation_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watch_history', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_recommendation_profiles', schema=None) as batch_op:
        batch_op.drop_column('watch_history')

    # ### end Alembic commands ###
