"""add_wrapped_keys

Revision ID: 7c01ead0ba2b
Revises: d377d4ec5352
Create Date: 2026-02-22 11:57:38.387351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c01ead0ba2b'
down_revision: Union[str, Sequence[str], None] = 'd377d4ec5352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('recipient_key', sa.Text(), nullable=True))
    op.add_column('chat_messages', sa.Column('sender_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'sender_key')
    op.drop_column('chat_messages', 'recipient_key')
    # ### end Alembic commands ###
