"""Add payout requests table

Revision ID: 87f6c7656bb5
Revises: 2e5874e941aa
Create Date: 2026-04-07 00:46:05.884885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f6c7656bb5'
down_revision: Union[str, Sequence[str], None] = '2e5874e941aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payout_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('bank_details', sa.Text(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_requests_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_requests_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_requests_wallet_id'), ['wallet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payout_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_requests_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_payout_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_payout_requests_status'))
        batch_op.drop_index(batch_op.f('ix_payout_requests_requested_at'))
        batch_op.drop_index(batch_op.f('ix_payout_requests_id'))

    op.drop_table('payout_requests')
    # ### end Alembic commands ###
