"""Add missing columns to users

Revision ID: abdefa368e36
Revises: 7cb96200572b
Create Date: 2026-04-28 10:24:45.757115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abdefa368e36'
down_revision: Union[str, Sequence[str], None] = '7cb96200572b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_country'), ['country'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_country'))
        batch_op.drop_column('country')

    # ### end Alembic commands ###
