"""add_recommendation_engine_tables

Revision ID: b1506accc1d5
Revises: 3a5babf76aab
Create Date: 2026-04-16 02:01:24.405765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1506accc1d5'
down_revision: Union[str, Sequence[str], None] = '3a5babf76aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recommendation_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_affinity', sa.Text(), nullable=True),
    sa.Column('seen_video_ids', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_recommendation_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_recommendation_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_recommendation_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('video_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('watch_time', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('replayed', sa.Boolean(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('skipped_fast', sa.Boolean(), nullable=True),
    sa.Column('interaction_score', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_interactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_interactions_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_interactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_interactions_video_id'), ['video_id'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_creator_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_subscriber_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subscriber_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('monthly_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('next_billing_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('subscriptions_creator_id_fkey')),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], name=op.f('subscriptions_subscriber_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscriptions_pkey'))
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_subscriber_id'), ['subscriber_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_creator_id'), ['creator_id'], unique=False)

    with op.batch_alter_table('video_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_interactions_video_id'))
        batch_op.drop_index(batch_op.f('ix_video_interactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_video_interactions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_video_interactions_id'))

    op.drop_table('video_interactions')
    with op.batch_alter_table('user_recommendation_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_recommendation_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_recommendation_profiles_id'))

    op.drop_table('user_recommendation_profiles')
    # ### end Alembic commands ###
