"""Add indexes and caching columns for performance

Revision ID: de8fb49fe9ad
Revises: 4c7e702c81d7
Create Date: 2026-04-06 23:22:30.947949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de8fb49fe9ad'
down_revision: Union[str, Sequence[str], None] = '4c7e702c81d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_video_id'), ['video_id'], unique=False)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_likes_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_video_id'), ['video_id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comments_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_discovery_score'), ['discovery_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_original_post_id'), ['original_post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comments_count', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_videos_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_discovery_score'), ['discovery_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_video_type'), ['video_type'], unique=False)

    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_views_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_views_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_views_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_views_video_id'))
        batch_op.drop_index(batch_op.f('ix_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_views_post_id'))

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_video_type'))
        batch_op.drop_index(batch_op.f('ix_videos_status'))
        batch_op.drop_index(batch_op.f('ix_videos_owner_id'))
        batch_op.drop_index(batch_op.f('ix_videos_discovery_score'))
        batch_op.drop_index(batch_op.f('ix_videos_created_at'))
        batch_op.drop_column('comments_count')
        batch_op.drop_column('likes_count')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_owner_id'))
        batch_op.drop_index(batch_op.f('ix_posts_original_post_id'))
        batch_op.drop_index(batch_op.f('ix_posts_discovery_score'))
        batch_op.drop_index(batch_op.f('ix_posts_created_at'))
        batch_op.drop_column('comments_count')
        batch_op.drop_column('likes_count')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_video_id'))
        batch_op.drop_index(batch_op.f('ix_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_likes_post_id'))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_video_id'))
        batch_op.drop_index(batch_op.f('ix_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_comments_parent_id'))
        batch_op.drop_index(batch_op.f('ix_comments_owner_id'))

    # ### end Alembic commands ###
