import React, { useEffect, useState } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { CheckCircle, XCircle, Clock, Loader, ArrowRight, Wallet, Crown } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { verifyDeposit, verifyProSubscription } from '../api';
import { useNotification } from '../context/NotificationContext';

/*
 * PaymentCallback — /payment
 *
 * Paystack redirects the user's browser here after a hosted-page checkout.
 * URL params:
 *   ?status=pending&reference=xxx   — payment may have gone through
 *   ?status=cancelled               — user closed Paystack popup
 *
 * We auto-detect the payment type from the reference prefix (if present),
 * or fall back to verifyDeposit as the safer default.
 */

const STATES = {
  LOADING:   'loading',
  SUCCESS:   'success',
  FAILED:    'failed',
  CANCELLED: 'cancelled',
};

export default function PaymentCallback() {
  const [searchParams] = useSearchParams();
  const navigate        = useNavigate();
  const { token, user, refreshUser } = useAuth();
  const { showNotification } = useNotification();

  const [state,   setState]   = useState(STATES.LOADING);
  const [message, setMessage] = useState('');
  const [detail,  setDetail]  = useState('');
  const [amount,  setAmount]  = useState(null);
  const [type,    setType]    = useState('deposit'); // 'deposit' | 'pro_subscription'

  const status    = searchParams.get('status');
  const reference = searchParams.get('reference');

  useEffect(() => {
    if (status === 'cancelled' || !reference) {
      setState(STATES.CANCELLED);
      setMessage('Payment Cancelled');
      setDetail("You closed the payment window before completing. No charge was made.");
      return;
    }

    if (!token) {
      // User isn't logged in — redirect to login then come back
      navigate(`/login?next=/payment?status=${status}&reference=${reference}`);
      return;
    }

    verifyPayment();
  }, [reference, status, token]);

  const verifyPayment = async () => {
    setState(STATES.LOADING);
    try {
      // Heuristic: references generated by JoinProV2 don't have a prefix,
      // but the metadata on the transaction will have payment_type set.
      // We try deposit first, and if the server returns a pro_subscription
      // transaction_type, we refresh the user profile too.
      const resp = await verifyDeposit(reference, token);

      if (resp.id) {
        const txType = resp.transaction_type || 'deposit';
        setType(txType);
        setAmount(Number(resp.amount));

        if (txType === 'pro_subscription') {
          await refreshUser?.();
          setState(STATES.SUCCESS);
          setMessage('Welcome to Monteeq Pro! 🎉');
          setDetail('Your Pro membership is now active. Enjoy 4K uploads, Gold Challenges, and 0% commission.');
          showNotification('Upgraded to Monteeq Pro!', 'success');
        } else {
          setState(STATES.SUCCESS);
          setMessage('Wallet Funded!');
          setDetail(`₦${Number(resp.amount).toLocaleString('en-NG', { minimumFractionDigits: 2 })} has been added to your wallet.`);
          showNotification('Wallet funded successfully!', 'success');
        }
      } else {
        // Server returned an error body
        const errMsg = resp.detail || 'Payment verification failed. Please contact support.';
        setState(STATES.FAILED);
        setMessage('Verification Failed');
        setDetail(errMsg);
      }
    } catch (err) {
      setState(STATES.FAILED);
      setMessage('Something Went Wrong');
      setDetail(err.message || 'Could not verify your payment. Please contact support.');
    }
  };

  /* ── Derived UI values ───────────────────────────────────────────── */
  const isPro = type === 'pro_subscription';

  const icon = {
    [STATES.LOADING]:   <Loader size={64} className="pcb-spin" />,
    [STATES.SUCCESS]:   isPro ? <Crown size={64} /> : <CheckCircle size={64} />,
    [STATES.FAILED]:    <XCircle size={64} />,
    [STATES.CANCELLED]: <Clock size={64} />,
  }[state];

  const palette = {
    [STATES.LOADING]:   { icon: '#6366f1', bg: 'rgba(99,102,241,0.12)', bar: '#6366f1' },
    [STATES.SUCCESS]:   isPro
      ? { icon: '#ffd700', bg: 'rgba(255,215,0,0.12)', bar: '#ffd700' }
      : { icon: '#22c55e', bg: 'rgba(34,197,94,0.12)',  bar: '#22c55e' },
    [STATES.FAILED]:    { icon: '#ef4444', bg: 'rgba(239,68,68,0.12)', bar: '#ef4444' },
    [STATES.CANCELLED]: { icon: '#94a3b8', bg: 'rgba(148,163,184,0.12)', bar: '#94a3b8' },
  }[state];

  return (
    <div style={styles.page}>
      {/* Ambient glow */}
      <div style={{ ...styles.glow, background: `radial-gradient(ellipse at 50% 0%, ${palette.bar}33 0%, transparent 70%)` }} />

      <div style={styles.card}>
        {/* Top accent bar */}
        <div style={{ ...styles.accentBar, background: palette.bar }} />

        {/* Icon */}
        <div style={{ ...styles.iconRing, background: palette.bg, color: palette.icon }}>
          {icon}
        </div>

        {/* Content */}
        <div style={styles.content}>
          {state === STATES.LOADING ? (
            <>
              <h1 style={styles.title}>Verifying Payment</h1>
              <p style={styles.subtitle}>Please wait — we're confirming your payment with Paystack…</p>
              <div style={styles.progressBar}>
                <div style={{ ...styles.progressFill, background: palette.bar }} />
              </div>
            </>
          ) : (
            <>
              <h1 style={styles.title}>{message}</h1>
              <p style={styles.subtitle}>{detail}</p>

              {state === STATES.SUCCESS && amount && !isPro && (
                <div style={{ ...styles.amountBadge, color: palette.icon, borderColor: `${palette.icon}33` }}>
                  <Wallet size={16} />
                  ₦{amount.toLocaleString('en-NG', { minimumFractionDigits: 2 })} credited
                </div>
              )}

              {state === STATES.SUCCESS && isPro && (
                <div style={{ ...styles.amountBadge, color: '#ffd700', borderColor: 'rgba(255,215,0,0.3)' }}>
                  <Crown size={16} />
                  Monteeq Pro Active
                </div>
              )}

              {state === STATES.FAILED && reference && (
                <p style={styles.refText}>Reference: <code style={styles.code}>{reference}</code></p>
              )}

              <div style={styles.actions}>
                {state === STATES.SUCCESS && isPro && (
                  <button id="pcb-explore-pro" style={{ ...styles.btn, ...styles.btnPrimary, background: 'linear-gradient(135deg, #ffd700, #ff8c00)', color: '#000' }}
                    onClick={() => navigate('/pro')}>
                    Explore Pro <ArrowRight size={16} />
                  </button>
                )}
                {state === STATES.SUCCESS && !isPro && (
                  <button id="pcb-go-wallet" style={{ ...styles.btn, ...styles.btnPrimary }}
                    onClick={() => navigate('/monetization')}>
                    Go to Wallet <ArrowRight size={16} />
                  </button>
                )}
                {state === STATES.FAILED && (
                  <button id="pcb-retry" style={{ ...styles.btn, ...styles.btnDanger }}
                    onClick={verifyPayment}>
                    Retry Verification
                  </button>
                )}
                <button id="pcb-home" style={{ ...styles.btn, ...styles.btnGhost }}
                  onClick={() => navigate('/')}>
                  Back to Home
                </button>
              </div>
            </>
          )}
        </div>

        {/* Paystack trust badge */}
        <div style={styles.trust}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" style={{ opacity: 0.5 }}>
            <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
          Secured by Paystack
        </div>
      </div>
    </div>
  );
}

/* ── Styles ────────────────────────────────────────────────────────── */
const styles = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'var(--bg-primary, #0d0d0d)',
    padding: '2rem 1rem',
    position: 'relative',
    overflow: 'hidden',
  },
  glow: {
    position: 'absolute',
    inset: 0,
    pointerEvents: 'none',
    zIndex: 0,
    transition: 'background 0.6s ease',
  },
  card: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    maxWidth: '460px',
    background: 'var(--glass-bg, rgba(255,255,255,0.04))',
    backdropFilter: 'blur(24px)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: '24px',
    overflow: 'hidden',
    boxShadow: '0 32px 64px rgba(0,0,0,0.4)',
    animation: 'pcbFadeUp 0.5s cubic-bezier(.16,1,.3,1) both',
  },
  accentBar: {
    height: '4px',
    width: '100%',
    transition: 'background 0.5s ease',
  },
  iconRing: {
    width: '128px',
    height: '128px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '2.5rem auto 0',
    transition: 'all 0.4s ease',
  },
  content: {
    padding: '1.75rem 2.5rem 2rem',
    textAlign: 'center',
  },
  title: {
    fontSize: '1.75rem',
    fontWeight: 700,
    color: 'var(--text-primary, #fff)',
    margin: '1rem 0 0.5rem',
    letterSpacing: '-0.02em',
  },
  subtitle: {
    fontSize: '0.95rem',
    color: 'var(--text-secondary, rgba(255,255,255,0.6))',
    lineHeight: 1.6,
    margin: '0 0 1.5rem',
  },
  amountBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '1rem',
    fontWeight: 600,
    border: '1px solid',
    borderRadius: '50px',
    padding: '0.5rem 1.25rem',
    margin: '0 auto 1.5rem',
  },
  refText: {
    fontSize: '0.8rem',
    color: 'rgba(255,255,255,0.4)',
    marginBottom: '1.5rem',
    wordBreak: 'break-all',
  },
  code: {
    fontFamily: 'monospace',
    background: 'rgba(255,255,255,0.07)',
    padding: '0.15rem 0.4rem',
    borderRadius: '4px',
  },
  progressBar: {
    height: '4px',
    background: 'rgba(255,255,255,0.1)',
    borderRadius: '99px',
    overflow: 'hidden',
    margin: '1.5rem 0 0',
  },
  progressFill: {
    height: '100%',
    width: '100%',
    borderRadius: '99px',
    animation: 'pcbPulse 1.2s ease-in-out infinite',
  },
  actions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  btn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '0.9rem 1.5rem',
    borderRadius: '12px',
    fontSize: '0.95rem',
    fontWeight: 600,
    cursor: 'pointer',
    border: 'none',
    transition: 'all 0.2s ease',
  },
  btnPrimary: {
    background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    color: '#fff',
  },
  btnDanger: {
    background: 'rgba(239,68,68,0.15)',
    color: '#ef4444',
    border: '1px solid rgba(239,68,68,0.3)',
  },
  btnGhost: {
    background: 'rgba(255,255,255,0.05)',
    color: 'rgba(255,255,255,0.6)',
    border: '1px solid rgba(255,255,255,0.08)',
  },
  trust: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.4rem',
    fontSize: '0.75rem',
    color: 'rgba(255,255,255,0.35)',
    paddingBottom: '1.5rem',
  },
};

/* ── Keyframe injection (runs once) ─────────────────────────────────── */
if (typeof document !== 'undefined' && !document.getElementById('pcb-keyframes')) {
  const style = document.createElement('style');
  style.id = 'pcb-keyframes';
  style.textContent = `
    @keyframes pcbFadeUp {
      from { opacity: 0; transform: translateY(32px) scale(0.97); }
      to   { opacity: 1; transform: translateY(0)    scale(1); }
    }
    @keyframes pcbPulse {
      0%, 100% { opacity: 1; }
      50%       { opacity: 0.3; }
    }
    .pcb-spin {
      animation: pcbSpinAnim 1s linear infinite;
    }
    @keyframes pcbSpinAnim {
      from { transform: rotate(0deg); }
      to   { transform: rotate(360deg); }
    }
  `;
  document.head.appendChild(style);
}
